apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-documentserver-service
spec:
  selector:
    app: onlyoffice-documentserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
